# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Thu Dec 14 04:23:25 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(593, 583)
        Dialog.setMinimumSize(QtCore.QSize(593, 583))
        Dialog.setMaximumSize(QtCore.QSize(593, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        Dialog.setFont(font)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 571, 571))
        self.tabWidget.setMinimumSize(QtCore.QSize(571, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(571, 571))
        self.tabWidget.setObjectName("tabWidget")
        
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 541, 221))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 521, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_2 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 6, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 2, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 3)
        self.pushButton_4 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 7, 3, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 2, 1, 1)
        #self.headerCheck = QtGui.QCheckBox(self.gridLayoutWidget)
        #self.headerCheck.setChecked(True)
        #self.headerCheck.setObjectName("headerCheck")
        #self.gridLayout.addWidget(self.headerCheck, 4, 0, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 1, 1, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setAutoRepeatInterval(100)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 1, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 250, 541, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget.addTab(self.tab, "")

        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 250, 541, 281))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 541, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 521, 191))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ButtonOkPreproses = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.ButtonOkPreproses.setObjectName("ButtonOkPreproses")
        self.gridLayout_4.addWidget(self.ButtonOkPreproses, 3, 5, 1, 1)
        self.radioMissingValue = QtGui.QRadioButton(self.gridLayoutWidget_4)
        self.radioMissingValue.setChecked(True)
        self.radioMissingValue.setObjectName("radioMissingValue")
        self.gridLayout_4.addWidget(self.radioMissingValue, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 3, 0, 1, 1)
        self.radioOutlier = QtGui.QRadioButton(self.gridLayoutWidget_4)
        self.radioOutlier.setChecked(False)
        self.radioOutlier.setObjectName("radioOutlier")
        self.gridLayout_4.addWidget(self.radioOutlier, 0, 2, 1, 1)
        self.radioNormal = QtGui.QRadioButton(self.gridLayoutWidget_4)
        self.radioNormal.setObjectName("radioNormal")
        self.gridLayout_4.addWidget(self.radioNormal, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 3, 4, 1, 1)
        self.label_r = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_r.setObjectName("label_r")
        self.gridLayout_4.addWidget(self.label_r, 1, 0, 1, 1)
        self.lineEdit_r = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_r.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_r.setReadOnly(False)
        self.lineEdit_r.setObjectName("lineEdit_r")
        self.gridLayout_4.addWidget(self.lineEdit_r, 1, 1, 1, 1)
        self.label_Phi = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_Phi.setObjectName("label_Phi")
        self.gridLayout_4.addWidget(self.label_Phi, 2, 0, 1, 1)
        self.lineEdit_Phi = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_Phi.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_Phi.setFrame(True)
        self.lineEdit_Phi.setReadOnly(False)
        self.lineEdit_Phi.setObjectName("lineEdit_Phi")
        self.gridLayout_4.addWidget(self.lineEdit_Phi, 2, 1, 1, 1)
        self.radioDummy = QtGui.QRadioButton(self.gridLayoutWidget_4)
        self.radioDummy.setObjectName("radioDummy")
        self.gridLayout_4.addWidget(self.radioDummy, 0, 4, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")

        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_4 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 240, 541, 291))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 541, 221))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.spinBox = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox)
        self.pushButton_3 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.pushButton_3)
        self.gridLayout_3.addLayout(self.formLayout, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")

        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_3 = QtGui.QTableWidget(self.tab_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 250, 541, 281))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 541, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 521, 191))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.naiveRadio = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.naiveRadio.setChecked(True)
        self.naiveRadio.setObjectName("naiveRadio")
        self.gridLayout_2.addWidget(self.naiveRadio, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 3, 3, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 6, 4, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 5, 4, 1, 1)
        self.treeRadio = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.treeRadio.setObjectName("treeRadio")
        self.gridLayout_2.addWidget(self.treeRadio, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 6, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 1, 1, 1)
        self.backRadio = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.backRadio.setObjectName("backRadio")
        self.gridLayout_2.addWidget(self.backRadio, 0, 2, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 5, 1, 1, 1)
        self.normalRadio = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.normalRadio.setChecked(False)
        self.normalRadio.setObjectName("normalRadio")
        self.gridLayout_2.addWidget(self.normalRadio, 0, 3, 1, 1)
        self.K_foldingCheck = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.K_foldingCheck.setObjectName("K_foldingCheck")
        self.gridLayout_2.addWidget(self.K_foldingCheck, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.lineEdit_r.setDisabled(True)
        self.lineEdit_Phi.setDisabled(True)
        self.spinBox_2.setDisabled(True)
        self.semuaTable = [self.tableWidget, self.tableWidget_2,
                           self.tableWidget_3, self.tableWidget_4]
        

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Load File", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Class", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("Dialog", "Ordinal", None, QtGui.QApplication.UnicodeUTF8))
        #self.headerCheck.setText(QtGui.QApplication.translate("Dialog", "Header", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("Dialog", "Numeric", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("Dialog", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Load Data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "sda", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonOkPreproses.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.radioMissingValue.setText(QtGui.QApplication.translate("Dialog", "Missing Value", None, QtGui.QApplication.UnicodeUTF8))
        self.radioOutlier.setText(QtGui.QApplication.translate("Dialog", "Outlier", None, QtGui.QApplication.UnicodeUTF8))
        self.radioNormal.setText(QtGui.QApplication.translate("Dialog", "Normalize", None, QtGui.QApplication.UnicodeUTF8))
        self.label_r.setText(QtGui.QApplication.translate("Dialog", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Phi.setText(QtGui.QApplication.translate("Dialog", "Phi", None, QtGui.QApplication.UnicodeUTF8))
        self.radioDummy.setText(QtGui.QApplication.translate("Dialog", "Dummy Dump", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "PrePosesing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Banyak kolom", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Dialog", "PCA", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "PCA", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Klasifikasi", None, QtGui.QApplication.UnicodeUTF8))
        self.naiveRadio.setText(QtGui.QApplication.translate("Dialog", "Naive Bayes", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Dialog", "Predict", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Dialog", "Training", None, QtGui.QApplication.UnicodeUTF8))
        self.treeRadio.setText(QtGui.QApplication.translate("Dialog", "Decision Tree", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Akurasi :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.backRadio.setText(QtGui.QApplication.translate("Dialog", "BackPropagation", None, QtGui.QApplication.UnicodeUTF8))
        self.normalRadio.setText(QtGui.QApplication.translate("Dialog", "Regresi Logistic", None, QtGui.QApplication.UnicodeUTF8))
        self.K_foldingCheck.setText(QtGui.QApplication.translate("Dialog", "K-Folding", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Type :", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Klasifikasi", None, QtGui.QApplication.UnicodeUTF8))

